export const IDS_ELEMENTS_HTML = {
    "display-value": "display-value",
    "display-op": "display-op",
    "ac-key": "ac-key",
    "sup-key": "sup-key",
    "prec-key": "prec-key",
    "seven-key": "7",
    "eight-key": "8",
    "nine-key": "9",
    "multy-key": "x",
    "ford-key": "4",
    "five-key": "5",
    "six-key": "6",
    "--key": "-",
    "one-key": "1",
    "two-key": "2",
    "three-key": "3",
    "add-key": "+",
    "zero-key": "0",
    "point-key": ".",
    "equal-key": "="
}